"""
Signal data schemas.

Defines the structure for trading signals generated by strategies.
"""
from dataclasses import dataclass, field
from typing import Optional, Dict, Any, List
from datetime import datetime
from enum import Enum


class SignalDirection(Enum):
    """Signal direction."""
    LONG = "long"
    SHORT = "short"
    FLAT = "flat"
    NEUTRAL = "neutral"


class ConfidenceLevel(Enum):
    """Confidence levels for signals."""
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


@dataclass
class SignalSchema:
    """
    Base schema for signal data.

    This represents a research signal, NOT a trading recommendation.
    Trading recommendations are generated by the execution layer.
    """
    # Identity
    region_id: str
    date: str
    strategy: str

    # Signal content
    direction: SignalDirection
    strength: float  # Raw signal strength (z-score, % change, etc.)
    confidence: ConfidenceLevel

    # Data quality
    data_quality: float  # 0-1, overall data quality score
    sample_count: int  # Number of observations
    coverage_ratio: float  # Spatial/temporal coverage

    # Human-readable output
    signal: str  # Human-readable signal description
    thesis: str  # Economic thesis
    actionability: str  # "Actionable" or "Ignore"

    # Raw values
    raw_value: Optional[float] = None
    baseline_value: Optional[float] = None
    percentile_rank: Optional[float] = None

    # Metadata
    metadata: Optional[Dict[str, Any]] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "region_id": self.region_id,
            "date": self.date,
            "strategy": self.strategy,
            "direction": self.direction.value if isinstance(self.direction, SignalDirection) else self.direction,
            "strength": self.strength,
            "confidence": self.confidence.value if isinstance(self.confidence, ConfidenceLevel) else self.confidence,
            "data_quality": self.data_quality,
            "sample_count": self.sample_count,
            "coverage_ratio": self.coverage_ratio,
            "signal": self.signal,
            "thesis": self.thesis,
            "actionability": self.actionability,
            "raw_value": self.raw_value,
            "baseline_value": self.baseline_value,
            "percentile_rank": self.percentile_rank,
            "metadata": self.metadata or {},
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SignalSchema":
        """Create from dictionary."""
        # Convert string direction to enum
        direction = data.get("direction", "neutral")
        if isinstance(direction, str):
            try:
                direction = SignalDirection(direction.lower())
            except ValueError:
                direction = SignalDirection.NEUTRAL

        # Convert string confidence to enum
        confidence = data.get("confidence", "Low")
        if isinstance(confidence, str):
            try:
                confidence = ConfidenceLevel(confidence)
            except ValueError:
                confidence = ConfidenceLevel.LOW

        return cls(
            region_id=data["region_id"],
            date=data["date"],
            strategy=data.get("strategy", "unknown"),
            direction=direction,
            strength=float(data.get("strength", 0)),
            confidence=confidence,
            data_quality=float(data.get("data_quality", 0)),
            sample_count=int(data.get("sample_count", 0)),
            coverage_ratio=float(data.get("coverage_ratio", 0)),
            signal=data.get("signal", "No data"),
            thesis=data.get("thesis", ""),
            actionability=data.get("actionability", "Ignore"),
            raw_value=data.get("raw_value"),
            baseline_value=data.get("baseline_value"),
            percentile_rank=data.get("percentile_rank"),
            metadata=data.get("metadata"),
        )


@dataclass
class MetaSignalSchema(SignalSchema):
    """
    Meta signal combining multiple regions.

    Meta signals aggregate signals from multiple regions
    to generate a higher-level trading thesis.
    """
    meta_group: str = ""
    vote_score: float = 0.0
    constituents: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        data = super().to_dict()
        data.update({
            "meta_group": self.meta_group,
            "vote_score": self.vote_score,
            "constituents": self.constituents,
        })
        return data


__all__ = ["SignalSchema", "MetaSignalSchema", "SignalDirection", "ConfidenceLevel"]
